/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import database.BaseDeDatos;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Empleado;

/**
 *
 * @author diego
 */
public class centroAdministracion extends javax.swing.JFrame {
    
    private BaseDeDatos BD;
    private List<Empleado> empleados;

    /**
     * Creates new form centroAdminstracion
     */
    public centroAdministracion() {
        initComponents();
        BD = new BaseDeDatos();
        empleados = BD.getEmpleados();
        cargarEmpleados();
    }
    
    public centroAdministracion(BaseDeDatos bd) {
        initComponents();
        this.BD = bd;
        empleados = bd.getEmpleados();
        cargarEmpleados();
    }
    
    public centroAdministracion(List<Empleado> empleados) {
        initComponents();
        this.empleados = empleados;
        cargarEmpleados();
    }
    
    
    public JPanel getPanelCentroAsministracion(){ return this.panelCentroAdmin;}
    
    private void cargarEmpleados(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID del Empleado");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido Paterno");
        modelo.addColumn("ApellidoMaterno");
        modelo.addColumn("Puesto");
        
        this.tablaCentroAdmin.setModel(modelo);
        String data[] = new String [5];
        for(Empleado e: empleados){
            data[0] = String.valueOf(e.getIdEmpleado()) ;
            data[1] = e.getNombre();
            data[2] = e.getApellidoP();
            data[3] = e.getApellidoM();
            data[4] = String.valueOf(e.getId_puesto());
            modelo.addRow(data); //Enviamos una fila al modelo;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentroAdmin = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCentroAdmin = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCentroAdmin.setPreferredSize(new java.awt.Dimension(300, 80));
        panelCentroAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaCentroAdmin.setAutoCreateRowSorter(true);
        tablaCentroAdmin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablaCentroAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Numero de empleado", "Nombre", "Apellido paterno", "Apellido materno", "Puesto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaCentroAdmin);

        panelCentroAdmin.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 480));

        getContentPane().add(panelCentroAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(centroAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(centroAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(centroAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(centroAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new centroAdministracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelCentroAdmin;
    private javax.swing.JTable tablaCentroAdmin;
    // End of variables declaration//GEN-END:variables
}
