/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import database.BaseDeDatos;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Producto;

/**
 *
 * @author diego
 */
public class centroAlmacen extends javax.swing.JFrame {
    
    private BaseDeDatos BD;
    private List<Producto> productos;

    /**
     * Creates new form centroAlmacen
     */
    public centroAlmacen() {
        initComponents();
        BD = new BaseDeDatos();
        productos = BD.getProductos();        
        cargarProductos();
    }
    
    public centroAlmacen(BaseDeDatos bd) {
        initComponents();
        this.BD = bd;
        productos = bd.getProductos();        
        cargarProductos();
    }
    
    public centroAlmacen(List<Producto> productos) {
        initComponents();
        this.productos = productos;        
        cargarProductos();
    }
    
    public JPanel getPanelCentroAlmacen(){ return this.panelCentroAlmacen;}
    
    private void cargarProductos(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Costo");
        modelo.addColumn("Precio");
        modelo.addColumn("Categoria");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Existencia");  
        this.tablaAlmacenProductos.setModel(modelo);        
        String data[] = new String [7];        
        for(Producto p: productos){
            data[0] = String.valueOf(p.getCodigo() );
            data[1] = p.getNombre();
            data[2] = String.valueOf(p.getPrecioC() ) ;
            data[3] = String.valueOf(p.getPrecioV() ) ; 
            data[4] = convertirCategoria(p);
            data[5] = p.getDescripcion();
            data[6] =String.valueOf( p.getExistencia() );            
            modelo.addRow(data); //Enviamos una fila al modelo;
        }        
    }
    
    private String convertirCategoria(Producto p){
        String c="-";
        if(p.getCategoria() ==1){ c="Telefonia"; return c; }
        if(p.getCategoria() ==2){ c="Computo"; return c; }
        if(p.getCategoria() ==3){ c="Tablets"; return c; }
        if(p.getCategoria() ==4){ c="Accesorios"; return c; }
        if(p.getCategoria() ==5){ c="Otros";  return c; }
        return c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentroAlmacen = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAlmacenProductos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCentroAlmacen.setBackground(new java.awt.Color(255, 255, 255));
        panelCentroAlmacen.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabla de almacen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Light", 1, 14))); // NOI18N
        panelCentroAlmacen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaAlmacenProductos.setAutoCreateRowSorter(true);
        tablaAlmacenProductos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablaAlmacenProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Costo", "Precio", "Categoria", "Descripcion", "Existencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaAlmacenProductos);

        panelCentroAlmacen.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 480));

        getContentPane().add(panelCentroAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(centroAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(centroAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(centroAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(centroAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new centroAlmacen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelCentroAlmacen;
    private javax.swing.JTable tablaAlmacenProductos;
    // End of variables declaration//GEN-END:variables
}
