/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controler.ControladorBD;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import model.Cliente;

/**
 *
 * @author Wilver
 */
public class dlcCambiarCliente extends javax.swing.JDialog {
    
    private lateralCajero lCajero;
    private Cliente nuevoCL;
    /**
     * Creates new form dlcCambiarCliente
     */
    public dlcCambiarCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    //Constrictor principal
    public dlcCambiarCliente(java.awt.Frame parent, boolean modal, lateralCajero latCaja) {
        super(parent, modal);
        initComponents();
        this.lCajero = latCaja;
    }
    
    private void limpiarCampos(){
        this.txtID.setText("");
        this.lblCorreo.setText("Correo electronico: ");
        this.lblID.setText("ID de cliente: ");
        this.lblNombre.setText("Nombre: ");
        this.btnAceptar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCambiarCliente = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAceptar = new javax.swing.JButton();
        lblCorreo = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CAMBIAR DE CLIENTE");

        panelCambiarCliente.setBackground(new java.awt.Color(255, 255, 255));
        panelCambiarCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 63, 100));
        jLabel9.setText("MY STORE");
        panelCambiarCliente.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (8).png"))); // NOI18N
        panelCambiarCliente.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 37, 60));
        panelCambiarCliente.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 370, 10));

        btnAceptar.setBackground(new java.awt.Color(0, 63, 100));
        btnAceptar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.setEnabled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        panelCambiarCliente.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 90, -1));

        lblCorreo.setFont(new java.awt.Font("Roboto Slab", 1, 12)); // NOI18N
        lblCorreo.setText("Correo electronico:");
        panelCambiarCliente.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        txtID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtID.setBorder(null);
        txtID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtIDMousePressed(evt);
            }
        });
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        panelCambiarCliente.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 290, 30));

        jLabel1.setBackground(new java.awt.Color(0, 63, 100));
        jLabel1.setOpaque(true);
        panelCambiarCliente.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 36, 370, 6));

        jLabel3.setFont(new java.awt.Font("Roboto Slab", 0, 18)); // NOI18N
        jLabel3.setText("Cambiar cliente");
        panelCambiarCliente.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 4, 170, 30));

        jLabel6.setForeground(new java.awt.Color(255, 255, 102));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (11).png"))); // NOI18N
        panelCambiarCliente.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, -5, 30, 40));

        lblID.setFont(new java.awt.Font("Roboto Slab", 1, 12)); // NOI18N
        lblID.setText("ID de cliente:");
        panelCambiarCliente.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel11.setText("Telefono:");
        panelCambiarCliente.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 56, -1, 20));
        panelCambiarCliente.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 340, 10));

        lblNombre.setFont(new java.awt.Font("Roboto Slab", 1, 12)); // NOI18N
        lblNombre.setText("Nombre:");
        panelCambiarCliente.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCambiarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCambiarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDMousePressed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // READY
        String tel = "-";
        
        if(txtID.getText().isBlank() || txtID.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese un TELEFONO de un cliente", "CAMPO INCOMPLETO", 2); //Advertencia
            limpiarCampos();
        }else{
            
            try{
                tel = txtID.getText();
                ControladorBD cbd = new ControladorBD();
                nuevoCL = cbd.buscarTelefonoCliente(tel);
                if(nuevoCL == null){
                    JOptionPane.showMessageDialog(null, "El TELEFONO ingresado no corresponde a ningun cliente", "CLIENTE NO ENCONTRADO", 2); //Advertencia
                    this.limpiarCampos();
                }else{
                    this.lblCorreo.setText("Correo electronico: " + nuevoCL.getCorreo());
                    this.lblID.setText("ID de cliente: " + String.valueOf(nuevoCL.getId_cliente()));
                    this.lblNombre.setText("Nombre: " + nuevoCL.getNombre()  );
                    this.btnAceptar.setEnabled(true);
                }
                
            } catch(HeadlessException e){
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "El TELEFONO ingresado no es una entrada valida", "ENTRADA INVALIDA", 2); //Advertencia
                this.limpiarCampos(); 
            }
        }        
        
    }//GEN-LAST:event_txtIDActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        this.lCajero.cambiarClienteLogueado(nuevoCL);
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlcCambiarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlcCambiarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlcCambiarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlcCambiarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlcCambiarCliente dialog = new dlcCambiarCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel panelCambiarCliente;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
