/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

/**
 *
 * @author Wilver
 */
public class dlcCobrarCuenta extends javax.swing.JDialog {

    /**
     * Creates new form dlcCobrarCuenta
     */
    public dlcCobrarCuenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCobrarCuenta = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCapturarDescuento = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lblSuma1 = new javax.swing.JLabel();
        lblResta1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblSuma2 = new javax.swing.JLabel();
        lblResta2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblSuma3 = new javax.swing.JLabel();
        lblResta3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblSuma4 = new javax.swing.JLabel();
        lblResta4 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblSuma5 = new javax.swing.JLabel();
        lblResta5 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblSuma6 = new javax.swing.JLabel();
        lblResta6 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtPago = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtCambio = new javax.swing.JTextField();
        btnCobrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("COBRAR ESTA CUENTA");

        panelCobrarCuenta.setBackground(new java.awt.Color(255, 255, 255));
        panelCobrarCuenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Slab", 0, 18)); // NOI18N
        jLabel3.setText("Cobrar Cuenta");
        panelCobrarCuenta.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 40));

        jLabel1.setBackground(new java.awt.Color(0, 63, 100));
        jLabel1.setOpaque(true);
        panelCobrarCuenta.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 740, 10));

        jLabel6.setForeground(new java.awt.Color(255, 255, 102));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (11).png"))); // NOI18N
        panelCobrarCuenta.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 30, 30));
        panelCobrarCuenta.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 740, 10));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 63, 100));
        jLabel9.setText("MY STORE");
        panelCobrarCuenta.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, -1, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (8).png"))); // NOI18N
        panelCobrarCuenta.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 37, 60));

        btnCapturarDescuento.setBackground(new java.awt.Color(255, 255, 51));
        btnCapturarDescuento.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        btnCapturarDescuento.setText("Capturar Descuento");
        btnCapturarDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapturarDescuentoActionPerformed(evt);
            }
        });
        panelCobrarCuenta.add(btnCapturarDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 150, -1));

        lblTotal.setFont(new java.awt.Font("Roboto Slab", 1, 48)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText("0.00");
        panelCobrarCuenta.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 320, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Slab", 1, 48)); // NOI18N
        jLabel4.setText("Total:  $ ");
        panelCobrarCuenta.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 200, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Denominaciones en billetes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Slab", 0, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/1000 (2).jpg"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lblSuma1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (48).png"))); // NOI18N
        lblSuma1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(lblSuma1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 30, 20));

        lblResta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (48).png"))); // NOI18N
        lblResta1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(lblResta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 30, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/500 (1).png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jLabel16.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        jLabel16.setText("0");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 10, -1));

        lblSuma2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (48).png"))); // NOI18N
        lblSuma2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(lblSuma2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 30, 20));

        lblResta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (48).png"))); // NOI18N
        lblResta2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(lblResta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 30, 20));

        jLabel19.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        jLabel19.setText("0");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 10, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/200 (1).jpg"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        lblSuma3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (48).png"))); // NOI18N
        lblSuma3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(lblSuma3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 30, 20));

        lblResta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (48).png"))); // NOI18N
        lblResta3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(lblResta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 30, 20));

        jLabel22.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        jLabel22.setText("0");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 10, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/100 (1).jpg"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        lblSuma4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (48).png"))); // NOI18N
        lblSuma4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(lblSuma4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 30, 20));

        lblResta4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (48).png"))); // NOI18N
        lblResta4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(lblResta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 30, 20));

        jLabel25.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        jLabel25.setText("0");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 10, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/50 (1).jpg"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        lblSuma5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (48).png"))); // NOI18N
        lblSuma5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(lblSuma5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 30, 20));

        lblResta5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (48).png"))); // NOI18N
        lblResta5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(lblResta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 30, 20));

        jLabel28.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        jLabel28.setText("0");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 10, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/20 (1).jpg"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        lblSuma6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (48).png"))); // NOI18N
        lblSuma6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(lblSuma6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 30, 20));

        lblResta6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (48).png"))); // NOI18N
        lblResta6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(lblResta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 30, 20));

        jLabel31.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        jLabel31.setText("0");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 10, -1));

        panelCobrarCuenta.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 510, 140));

        jLabel32.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        jLabel32.setText("Pago con:    $");
        panelCobrarCuenta.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 100, 20));

        txtPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagoActionPerformed(evt);
            }
        });
        panelCobrarCuenta.add(txtPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 130, 20));

        jLabel33.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        jLabel33.setText("Cambio:    $");
        panelCobrarCuenta.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 90, 20));

        txtCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCambioActionPerformed(evt);
            }
        });
        panelCobrarCuenta.add(txtCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 130, 20));

        btnCobrar.setBackground(new java.awt.Color(51, 255, 51));
        btnCobrar.setFont(new java.awt.Font("Roboto Slab", 0, 14)); // NOI18N
        btnCobrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (16).png"))); // NOI18N
        btnCobrar.setText("Cobrar");
        btnCobrar.setOpaque(true);
        btnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarActionPerformed(evt);
            }
        });
        panelCobrarCuenta.add(btnCobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 120, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelCobrarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelCobrarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapturarDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturarDescuentoActionPerformed
        // TODO add your handling code here:
        dlcAplicarDescuento dialog = new dlcAplicarDescuento(new javax.swing.JFrame(), true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        
    }//GEN-LAST:event_btnCapturarDescuentoActionPerformed

    private void txtPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPagoActionPerformed

    private void txtCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCambioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCambioActionPerformed

    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
         //Enviar informacion al ticket
         
         
        dlcTicket dialog = new dlcTicket(new javax.swing.JFrame(), true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnCobrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlcCobrarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlcCobrarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlcCobrarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlcCobrarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlcCobrarCuenta dialog = new dlcCobrarCuenta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapturarDescuento;
    private javax.swing.JButton btnCobrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblResta1;
    private javax.swing.JLabel lblResta2;
    private javax.swing.JLabel lblResta3;
    private javax.swing.JLabel lblResta4;
    private javax.swing.JLabel lblResta5;
    private javax.swing.JLabel lblResta6;
    private javax.swing.JLabel lblSuma1;
    private javax.swing.JLabel lblSuma2;
    private javax.swing.JLabel lblSuma3;
    private javax.swing.JLabel lblSuma4;
    private javax.swing.JLabel lblSuma5;
    private javax.swing.JLabel lblSuma6;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panelCobrarCuenta;
    private javax.swing.JTextField txtCambio;
    private javax.swing.JTextField txtPago;
    // End of variables declaration//GEN-END:variables
}
