/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

/**
 *
 * @author Wilver
 */
public class dlcTicket extends javax.swing.JDialog {

    /**
     * Creates new form dlcTicket
     */
    public dlcTicket(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTicket = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TICKET");

        panelTicket.setBackground(new java.awt.Color(255, 255, 255));
        panelTicket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 63, 100));
        jLabel1.setOpaque(true);
        panelTicket.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 10, 710));

        jLabel2.setBackground(new java.awt.Color(0, 63, 100));
        jLabel2.setOpaque(true);
        panelTicket.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 10, 720));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 63, 100));
        jLabel9.setText("MY STORE SA DE CV");
        panelTicket.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (9).png"))); // NOI18N
        panelTicket.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, 70));

        jLabel3.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel3.setText("--------------------------------------------------------------------------------");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelTicket.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 320, 20));

        jLabel4.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel4.setText("R. F. C. DMRH041224-RHM");
        panelTicket.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, 20));

        jLabel6.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel6.setText("SUCURSAL OAXACA 1 (001)");
        panelTicket.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, 20));

        jLabel7.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel7.setText("Calzada Francisco I. Madero 1332");
        panelTicket.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CANT.", "ARTICULO", "PRECIO UNI", "SUBTOTAL"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        panelTicket.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 217, 300, 190));

        jLabel10.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel10.setText("Oaxaca de Juarez, Oaxaca");
        panelTicket.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, 20));

        jLabel11.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel11.setText("0.00");
        panelTicket.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, -1, 20));

        jLabel12.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel12.setText("21:23");
        panelTicket.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 570, 70, 20));

        jLabel13.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel13.setText("0.00");
        panelTicket.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, -1, 20));

        jLabel14.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel14.setText("TOTAL M.N. $");
        panelTicket.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, 20));

        jLabel15.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel15.setText("0.00");
        panelTicket.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, -1, 20));

        jLabel16.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel16.setText("0.00");
        panelTicket.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, -1, 20));

        jLabel17.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel17.setText("Efectivo $");
        panelTicket.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, -1, 20));

        jLabel19.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel19.setText("Cambio $");
        panelTicket.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, -1, 20));

        jLabel18.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel18.setText("CAMBIO EN MONEDERO:");
        panelTicket.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, -1, 20));

        jLabel20.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel20.setText("LE ATENDIO:");
        panelTicket.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, 20));

        jLabel21.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel21.setText("ROQUE HERNANDEZ DIEGO");
        panelTicket.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 550, 220, 20));

        jLabel22.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel22.setText("FOLIO: 000001");
        panelTicket.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, -1, 20));

        jLabel23.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel23.setText("19/05/2024");
        panelTicket.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, 70, 20));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (50).png"))); // NOI18N
        jLabel24.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelTicket.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlcTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlcTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlcTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlcTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlcTicket dialog = new dlcTicket(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelTicket;
    // End of variables declaration//GEN-END:variables
}
