/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controler.ControladorBD;
import javax.swing.JOptionPane;
import model.Empleado;

/**
 *
 * @author Wilver
 */
public class dldBuscarEmpleado extends javax.swing.JDialog {
    
    //OK    
    //private ControladorBD con;
    private int id =-1;

    /**
     * Creates new form dldBuscarEmpleado
     */
    public dldBuscarEmpleado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    private void limpiarCampos(){
        this.txtApellidoMaterno.setText("");
        this.txtApellidoPaterno.setText("");
        this.txtCodigoDeEmpleado.setText("");
        this.txtNombre.setText("");
        this.txtPuesto.setText("");
        this.txtUsuario.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBuscarEmpleado = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigoDeEmpleado = new javax.swing.JTextField();
        txtPuesto = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        txtApellidoPaterno = new javax.swing.JLabel();
        txtApellidoMaterno = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BUSCAR EMPLEADO");

        panelBuscarEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Slab", 0, 18)); // NOI18N
        jLabel3.setText("Buscar Empleado");
        panelBuscarEmpleado.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 170, 30));

        jLabel6.setForeground(new java.awt.Color(255, 255, 102));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (11).png"))); // NOI18N
        panelBuscarEmpleado.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 30, 40));

        jLabel8.setFont(new java.awt.Font("Roboto Slab", 1, 12)); // NOI18N
        jLabel8.setText("ID Empleado:");
        panelBuscarEmpleado.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 30));

        jLabel1.setBackground(new java.awt.Color(0, 63, 100));
        jLabel1.setOpaque(true);
        panelBuscarEmpleado.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 36, 410, 10));

        txtCodigoDeEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCodigoDeEmpleado.setForeground(new java.awt.Color(0, 0, 102));
        txtCodigoDeEmpleado.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCodigoDeEmpleado.setBorder(null);
        txtCodigoDeEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCodigoDeEmpleadoMousePressed(evt);
            }
        });
        txtCodigoDeEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoDeEmpleadoActionPerformed(evt);
            }
        });
        panelBuscarEmpleado.add(txtCodigoDeEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 240, 30));

        txtPuesto.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        panelBuscarEmpleado.add(txtPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 210, 40));

        btnAceptar.setBackground(new java.awt.Color(0, 63, 100));
        btnAceptar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        panelBuscarEmpleado.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 110, 30));
        panelBuscarEmpleado.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 410, 10));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (8).png"))); // NOI18N
        panelBuscarEmpleado.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 37, 60));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 63, 100));
        jLabel9.setText("MY STORE");
        panelBuscarEmpleado.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, 20));

        lbl5.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        lbl5.setText("Puesto:");
        panelBuscarEmpleado.add(lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 60, 40));

        lbl2.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        lbl2.setText("Apellido Paterno:");
        panelBuscarEmpleado.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 130, 40));

        lbl3.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        lbl3.setText("Apellido Materno:");
        panelBuscarEmpleado.add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 130, 40));

        lbl4.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        lbl4.setText("Usuario:");
        panelBuscarEmpleado.add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 60, 40));

        lbl1.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        lbl1.setText("Nombre:");
        panelBuscarEmpleado.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 70, 40));

        txtNombre.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        panelBuscarEmpleado.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 210, 40));

        txtApellidoPaterno.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        panelBuscarEmpleado.add(txtApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 210, 40));

        txtApellidoMaterno.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        panelBuscarEmpleado.add(txtApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 210, 40));

        txtUsuario.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        panelBuscarEmpleado.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 210, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoDeEmpleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoDeEmpleadoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoDeEmpleadoMousePressed

    private void txtCodigoDeEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoDeEmpleadoActionPerformed
        // TODO add your handling code here:
        //READY
        ControladorBD conbd= new ControladorBD();
        if(txtCodigoDeEmpleado.getText().isBlank() || txtCodigoDeEmpleado.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese un ID de empleado", "CAMPO INCOMPLETO", 2); //Advertencia     
            this.limpiarCampos();
        }else{
            try{
                id = Integer.parseInt(this.txtCodigoDeEmpleado.getText());                
                Empleado empleado = conbd.buscarEmpleado(id);
                if (empleado == null) {
                    JOptionPane.showMessageDialog(null, "El ID ingresado no corresponde a ningun empleado", "EMPLEDO NO ENCONTRADO", 2); //Advertencia
                    this.limpiarCampos();
                } else {
                    this.txtNombre.setText(empleado.getNombre());
                    this.txtApellidoMaterno.setText(empleado.getApellidoM());
                    this.txtApellidoPaterno.setText(empleado.getApellidoP());
                    this.txtPuesto.setText(String.valueOf(empleado.getId_puesto()));
                    this.txtUsuario.setText(empleado.getUsuario());
                }                
            } catch(NumberFormatException e){
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "El ID ingresado no es una entrada valida", "ENTRADA INVALIDA", 2); //Advertencia
                this.limpiarCampos();
            }
            
        }
        
    }//GEN-LAST:event_txtCodigoDeEmpleadoActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dldBuscarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dldBuscarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dldBuscarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dldBuscarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dldBuscarEmpleado dialog = new dldBuscarEmpleado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JPanel panelBuscarEmpleado;
    private javax.swing.JLabel txtApellidoMaterno;
    private javax.swing.JLabel txtApellidoPaterno;
    private javax.swing.JTextField txtCodigoDeEmpleado;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtPuesto;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables
}
