/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controler.ControladorBD;
import javax.swing.JOptionPane;
import model.Empleado;

/**
 *
 * @author Wilver
 */
public class dldEditarEmpleado extends javax.swing.JDialog {
    
    //OK
    //private ControladorBD con;
    private int id=-1;
    private Empleado editEmpleado;
    /**
     * Creates new form dldEditarEmpleado
     */
    public dldEditarEmpleado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
         
    private void limpiarCampos(){
        this.txtID.setText("");
        this.txtApellidoMaterno.setText("");
        this.txtApellidoPaterno.setText("");
        this.txtContraseña.setText("");
        this.txtNombre.setText("");
        this.txtPuesto.setText("");
        this.txtUsuario.setText("");
    }
    
    private void activarEdicion(boolean bandera){
        this.btnEdicion.setEnabled(bandera);
        this.txtApellidoMaterno.setEnabled(bandera);
        this.txtApellidoPaterno.setEnabled(bandera);
        //this.txtContraseña.setEnabled(bandera);
        this.txtNombre.setEnabled(bandera);
        this.txtPuesto.setEnabled(bandera);
        //this.txtUsuario.setEnabled(bandera);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEditarEmpleado = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPuesto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtApellidoPaterno = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtApellidoMaterno = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnEdicion = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EDITAR EMPLEADO");

        panelEditarEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        panelEditarEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Slab", 0, 18)); // NOI18N
        jLabel3.setText("Edicion de trabajador");
        panelEditarEmpleado.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 210, 50));

        jLabel6.setForeground(new java.awt.Color(255, 255, 102));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (11).png"))); // NOI18N
        panelEditarEmpleado.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 30, 30));

        jLabel1.setBackground(new java.awt.Color(0, 63, 100));
        jLabel1.setOpaque(true);
        panelEditarEmpleado.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 420, 10));

        jLabel10.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel10.setText("ID:");
        panelEditarEmpleado.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 66, 40, 20));

        jLabel8.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel8.setText("Nombre:");
        panelEditarEmpleado.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 60, 30));

        txtNombre.setEnabled(false);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        panelEditarEmpleado.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 270, 30));

        txtPuesto.setEnabled(false);
        txtPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPuestoActionPerformed(evt);
            }
        });
        panelEditarEmpleado.add(txtPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 270, 30));

        jLabel11.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel11.setText("Contraseña:");
        panelEditarEmpleado.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 70, 30));

        jLabel13.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel13.setText("ID puesto:");
        panelEditarEmpleado.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 70, 30));

        txtApellidoPaterno.setEnabled(false);
        txtApellidoPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPaternoActionPerformed(evt);
            }
        });
        panelEditarEmpleado.add(txtApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 270, 30));

        jLabel14.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel14.setText("Apellido paterno:");
        panelEditarEmpleado.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 100, 30));

        txtApellidoMaterno.setEnabled(false);
        txtApellidoMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMaternoActionPerformed(evt);
            }
        });
        panelEditarEmpleado.add(txtApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 270, 30));

        jLabel15.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel15.setText("Apellido materno:");
        panelEditarEmpleado.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 100, 30));

        btnEdicion.setBackground(new java.awt.Color(0, 63, 100));
        btnEdicion.setFont(new java.awt.Font("Roboto Slab", 1, 12)); // NOI18N
        btnEdicion.setForeground(new java.awt.Color(255, 255, 255));
        btnEdicion.setText("Comfirmar Edicion");
        btnEdicion.setEnabled(false);
        btnEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdicionActionPerformed(evt);
            }
        });
        panelEditarEmpleado.add(btnEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 353, 140, 30));

        btnCancelar.setBackground(new java.awt.Color(0, 63, 100));
        btnCancelar.setFont(new java.awt.Font("Roboto Slab", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelEditarEmpleado.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 353, 110, 30));
        panelEditarEmpleado.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 420, 10));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 63, 100));
        jLabel9.setText("MY STORE");
        panelEditarEmpleado.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, -1, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (8).png"))); // NOI18N
        panelEditarEmpleado.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 37, 60));

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        panelEditarEmpleado.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 120, 30));

        jLabel12.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel12.setText("Usuario:");
        panelEditarEmpleado.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 60, 30));

        txtUsuario.setEnabled(false);
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        panelEditarEmpleado.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 270, 30));

        txtContraseña.setText("jPasswordField1");
        txtContraseña.setEnabled(false);
        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        panelEditarEmpleado.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 270, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEditarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEditarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPaternoActionPerformed

    private void txtApellidoMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMaternoActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // READY
        //ControladorBD conbd = new ControladorBD();
        boolean b = true;
        if(txtID.getText().isBlank() || txtID.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese un ID de trabajador", "CAMPO INCOMPLETO", 2); //Advertencia  
            this.limpiarCampos();
            this.activarEdicion(false);
        }else{
            
            try{
                id = Integer.parseInt(this.txtID.getText());                
                ControladorBD cbd = new ControladorBD();
                Empleado empleado = cbd.buscarEmpleado(id);                
                if(empleado == null){
                    JOptionPane.showMessageDialog(null, "El ID ingresado no corresponde a ningun empleado", "EMPLEDO NO ENCONTRADO", 2); //Advertencia
                    this.limpiarCampos();
                    this.activarEdicion(false);
                }else{
                    this.activarEdicion(true);
                    //Mostramos los datos del empleado
                    this.txtNombre.setText(empleado.getNombre());
                    this.txtApellidoMaterno.setText(empleado.getApellidoM());
                    this.txtApellidoPaterno.setText(empleado.getApellidoP());
                    this.txtPuesto.setText(String.valueOf(empleado.getId_puesto()));
                    this.txtUsuario.setText(empleado.getUsuario());
                    this.txtContraseña.setText(empleado.getContraseña());
                    editEmpleado = new Empleado(empleado);
                }                
                
            } catch(NumberFormatException e){
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "Ingrese un ID de trabajador valido", "ID INVALIDO", 2); //Advertencia  
                this.limpiarCampos();
                this.activarEdicion(false);
            }
        }            
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPuestoActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void btnEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdicionActionPerformed
        //READY
        if(this.txtID.getText().isBlank() || this.txtID.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese un ID de trabajador", "CAMPO INCOMPLETO", 2); //Advertencia
        } else{
            String n, ap, am, u,  p;
            n= this.txtNombre.getText();
            ap = this.txtApellidoPaterno.getText();
            am=this.txtApellidoMaterno.getText();
            u= this.txtUsuario.getText();
            //c= String.valueOf(this.txtContraseña.getPassword());            
            p = this.txtPuesto.getText();
            
            if(n.isBlank() || n.isEmpty() || ap.isBlank() || ap.isEmpty() || am.isBlank() || am.isEmpty() || u.isBlank() || u.isEmpty() || p.isBlank() || p.isEmpty()){
                JOptionPane.showMessageDialog(null, "No puede dejar campos en blaco", "CAMPOS INCOMPLETOS", 2); //Advertencia
            }else{
                ControladorBD conBD = new ControladorBD();
                try{
                    int idPuesto = Integer.parseInt(p);
                    if(idPuesto >= conBD.getnPuesto() || idPuesto <0 ){
                        //Mensaje de error puesto no existente
                        JOptionPane.showMessageDialog(null, "El id de puesto ingresado no corresponde a ningun puesto", "ID DE PUESTO INVALIDO", 2); //Advertencia
                    }else{                        
                        this.editEmpleado.setNombre(n);
                        this.editEmpleado.setApellidoP(ap);
                        this.editEmpleado.setApellidoM(am);
                        //this.editEmpleado.setUsuario(u);
                        this.editEmpleado.setId_puesto(idPuesto);
                        conBD.editarEmpleado(editEmpleado);
                         this.dispose();
                    }                    
                } catch(Exception e){
                    System.out.println(e);
                    JOptionPane.showMessageDialog(null, "El id de puesto no es una entrada valida", "CAMPO INVALIDO", 2); //Advertencia
                }
            }
        }

       
    }//GEN-LAST:event_btnEdicionActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dldEditarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dldEditarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dldEditarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dldEditarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dldEditarEmpleado dialog = new dldEditarEmpleado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEdicion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelEditarEmpleado;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPuesto;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
