/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

//import controler.ControladorConsultarPrecio;
import controler.ControladorProducto;
import java.awt.Color;
import javax.swing.JOptionPane;
import model.Producto;

/**
 *
 * @author Wilver
 */
public class dvgConsultarPrecio extends javax.swing.JDialog {
    //ControladorConsultarPrecio controlador;
    ControladorProducto cP;
    
    /**
     * Creates new form dvgConsultarPrecio
     */
    public dvgConsultarPrecio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    private void busqueda(){
        cP = new ControladorProducto();
        int id = Integer.parseInt(this.txtCodigoDeProducto.getText());
        //cP.existeProducto(id);
        if(cP.existeProducto(id)){
            Producto p = cP.bucarProducto(id);
            
            this.lblNombre.setText(p.getNombre());
            this.lblDescripcion.setText(p.getDescripcion());
            this.txtPrecio.setText( "$ " +String.valueOf(p.getPrecioV()) );
        } else{
            this.lblNombre.setText("Este producto no existe");
            this.lblDescripcion.setText("-");
            this.txtPrecio.setText("-");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelConsultarPrecio = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAceptar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCodigoDeProducto = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        txtPrecio = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CONSULTAR PRECIO DE UN PRODUCTO");

        panelConsultarPrecio.setBackground(new java.awt.Color(255, 255, 255));
        panelConsultarPrecio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 63, 100));
        jLabel9.setText("MY STORE");
        panelConsultarPrecio.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (8).png"))); // NOI18N
        panelConsultarPrecio.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 37, 60));
        panelConsultarPrecio.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 370, 10));

        btnAceptar.setBackground(new java.awt.Color(0, 63, 100));
        btnAceptar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        panelConsultarPrecio.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 90, -1));

        lblNombre.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        lblNombre.setText("Nombre del producto");
        panelConsultarPrecio.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 340, -1));

        jLabel1.setBackground(new java.awt.Color(0, 63, 100));
        jLabel1.setOpaque(true);
        panelConsultarPrecio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 36, 370, 6));

        jLabel3.setFont(new java.awt.Font("Roboto Slab", 0, 18)); // NOI18N
        jLabel3.setText("Consulta de precios");
        panelConsultarPrecio.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 4, 170, 30));

        jLabel6.setForeground(new java.awt.Color(255, 255, 102));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (11).png"))); // NOI18N
        panelConsultarPrecio.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, -5, 30, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Precio:");
        panelConsultarPrecio.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 40, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel8.setText("Producto:");
        panelConsultarPrecio.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txtCodigoDeProducto.setForeground(new java.awt.Color(204, 204, 204));
        txtCodigoDeProducto.setText("Introduce el codigo del producto");
        txtCodigoDeProducto.setBorder(null);
        txtCodigoDeProducto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoDeProductoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoDeProductoFocusLost(evt);
            }
        });
        txtCodigoDeProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCodigoDeProductoMousePressed(evt);
            }
        });
        txtCodigoDeProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoDeProductoActionPerformed(evt);
            }
        });
        panelConsultarPrecio.add(txtCodigoDeProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 200, 20));

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        panelConsultarPrecio.add(btnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        txtPrecio.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        txtPrecio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtPrecio.setText("$ 0.00");
        panelConsultarPrecio.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 100, -1));

        lblDescripcion.setFont(new java.awt.Font("Roboto Slab", 0, 14)); // NOI18N
        lblDescripcion.setText("Aqui se mostrara la descripcion del producto");
        panelConsultarPrecio.add(lblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 340, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelConsultarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelConsultarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 289, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoDeProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoDeProductoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoDeProductoMousePressed

    private void txtCodigoDeProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoDeProductoActionPerformed
        // TODO add your handling code here:
        this.busqueda();
    }//GEN-LAST:event_txtCodigoDeProductoActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        //Limpiar y cerrar
        //this.txtCodigoDeProducto.setText("Introduce el codigo del produto");
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtCodigoDeProductoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoDeProductoFocusGained
        // TODO add your handling code here:
        this.txtCodigoDeProducto.setText("");
        this.txtCodigoDeProducto.setForeground(Color.black);
    }//GEN-LAST:event_txtCodigoDeProductoFocusGained

    private void txtCodigoDeProductoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoDeProductoFocusLost
        // TODO add your handling code here:
        Color c = new Color(204,204,204);
        //this.txtCodigoDeProducto.setText("Introduce el codigo del producto");
        this.txtCodigoDeProducto.setForeground(c);
    }//GEN-LAST:event_txtCodigoDeProductoFocusLost

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        if(this.txtCodigoDeProducto.getText().isEmpty() || this.txtCodigoDeProducto.getText().isBlank()){
            JOptionPane.showMessageDialog(null, "Debe ingresar un codigo de producto ");
            this.txtCodigoDeProducto.setText("");
        }else{
            this.busqueda();
        }
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dvgConsultarPrecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dvgConsultarPrecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dvgConsultarPrecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dvgConsultarPrecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dvgConsultarPrecio dialog = new dvgConsultarPrecio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel panelConsultarPrecio;
    private javax.swing.JTextField txtCodigoDeProducto;
    private javax.swing.JLabel txtPrecio;
    // End of variables declaration//GEN-END:variables
}
