/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import graphics.GraficoInventario;
import graphics.GraficoMasVendido;
import graphics.GraficoMenosVendido;

/**
 *
 * @author Wilver
 */
public class dvgGrafica extends javax.swing.JDialog {

    /**
     * Creates new form dvgGrafica
     */
    public dvgGrafica(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGraficas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnInventario = new javax.swing.JButton();
        btnMasVendido = new javax.swing.JButton();
        btnMenosVendido = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GRAFICA DE VENTAS");

        panelGraficas.setBackground(new java.awt.Color(255, 255, 255));
        panelGraficas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Slab", 0, 18)); // NOI18N
        jLabel3.setText("Graficas");
        panelGraficas.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 40));

        jLabel1.setBackground(new java.awt.Color(0, 63, 100));
        jLabel1.setOpaque(true);
        panelGraficas.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 780, 10));

        jLabel6.setForeground(new java.awt.Color(255, 255, 102));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (11).png"))); // NOI18N
        panelGraficas.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 30, 30));
        panelGraficas.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 780, 10));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 63, 100));
        jLabel9.setText("MY STORE");
        panelGraficas.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 70, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (8).png"))); // NOI18N
        panelGraficas.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 40, 70));

        btnInventario.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        btnInventario.setForeground(new java.awt.Color(51, 51, 255));
        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (57).png"))); // NOI18N
        btnInventario.setText("Inventario por Categoría");
        btnInventario.setToolTipText("");
        btnInventario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInventario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInventario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        panelGraficas.add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, -1, 220));

        btnMasVendido.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        btnMasVendido.setForeground(new java.awt.Color(51, 255, 51));
        btnMasVendido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (55).png"))); // NOI18N
        btnMasVendido.setText("Producto Mas Vendido");
        btnMasVendido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMasVendido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMasVendido.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMasVendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasVendidoActionPerformed(evt);
            }
        });
        panelGraficas.add(btnMasVendido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        btnMenosVendido.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        btnMenosVendido.setForeground(new java.awt.Color(255, 0, 51));
        btnMenosVendido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (56).png"))); // NOI18N
        btnMenosVendido.setText("Producto Menos Vendido");
        btnMenosVendido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenosVendido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenosVendido.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMenosVendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosVendidoActionPerformed(evt);
            }
        });
        panelGraficas.add(btnMenosVendido, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, 220));

        jLabel2.setFont(new java.awt.Font("Roboto Slab", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 63, 100));
        jLabel2.setText("REPORTE GRAFICO SOBRE LOS PRODUCTOS");
        panelGraficas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelGraficas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelGraficas, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        // TODO add your handling code here:
        GraficoInventario example = new GraficoInventario();
        example.setSize(800, 600);
        example.setLocationRelativeTo(null);
            //example.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        example.setVisible(true);
        example.setAlwaysOnTop(true);
        this.dispose();
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnMasVendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasVendidoActionPerformed
        // TODO add your handling code here:
        GraficoMasVendido grafico = new GraficoMasVendido();
        grafico.setSize(800,600);
        grafico.setLocationRelativeTo(null);
        grafico.setVisible(true);
        grafico.setAlwaysOnTop(true);
        this.dispose();
    }//GEN-LAST:event_btnMasVendidoActionPerformed

    private void btnMenosVendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosVendidoActionPerformed
        // TODO add your handling code here:
        GraficoMenosVendido grafico = new GraficoMenosVendido();
        grafico.setSize(800,600);
        grafico.setLocationRelativeTo(null);
        grafico.setVisible(true);
        grafico.setAlwaysOnTop(true);
        this.dispose();
    }//GEN-LAST:event_btnMenosVendidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dvgGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dvgGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dvgGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dvgGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dvgGrafica dialog = new dvgGrafica(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnMasVendido;
    private javax.swing.JButton btnMenosVendido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelGraficas;
    // End of variables declaration//GEN-END:variables
}
