/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

/**
 *
 * @author Wilver
 */
public class dvgSuper extends javax.swing.JDialog {
    vistaGeneral vGeneral;
    /**
     * Creates new form dvgSuper
     * @param parent
     * @param modal
     * @param vG
     */
    //Cosntructor 
    public dvgSuper(java.awt.Frame parent, boolean modal, vistaGeneral vG) {
        super(parent, modal);
        initComponents();
        this.vGeneral=vG;
    }
    
    //Constructor de puebas
    public dvgSuper(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    
    private void revalidarVista(){
        vGeneral.getPanelCentral().removeAll();
        vGeneral.getPanelLateral().removeAll();
        vGeneral.revalidate();
        vGeneral.repaint(); 
        vGeneral.getPanelCentral().revalidate();
        vGeneral.getPanelCentral().repaint();
        vGeneral.getPanelLateral().revalidate();
        vGeneral.getPanelLateral().repaint();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnUsuarioCaja = new javax.swing.JButton();
        btnUsuarioAlmacen = new javax.swing.JButton();
        btnUsuarioAdministracion = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Slab", 0, 18)); // NOI18N
        jLabel3.setText("Cambiar Nivel de Usuario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, 40));

        btnUsuarioCaja.setBackground(new java.awt.Color(102, 204, 255));
        btnUsuarioCaja.setFont(new java.awt.Font("Roboto Slab", 0, 14)); // NOI18N
        btnUsuarioCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (17).png"))); // NOI18N
        btnUsuarioCaja.setText("Caja");
        btnUsuarioCaja.setOpaque(true);
        btnUsuarioCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioCajaActionPerformed(evt);
            }
        });
        jPanel1.add(btnUsuarioCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 170, 90));

        btnUsuarioAlmacen.setBackground(new java.awt.Color(255, 153, 153));
        btnUsuarioAlmacen.setFont(new java.awt.Font("Roboto Slab", 0, 14)); // NOI18N
        btnUsuarioAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (20).png"))); // NOI18N
        btnUsuarioAlmacen.setText("Almacen");
        btnUsuarioAlmacen.setOpaque(true);
        btnUsuarioAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioAlmacenActionPerformed(evt);
            }
        });
        jPanel1.add(btnUsuarioAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 170, 90));

        btnUsuarioAdministracion.setBackground(new java.awt.Color(255, 51, 255));
        btnUsuarioAdministracion.setFont(new java.awt.Font("Roboto Slab", 0, 14)); // NOI18N
        btnUsuarioAdministracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (24).png"))); // NOI18N
        btnUsuarioAdministracion.setText("Administracion");
        btnUsuarioAdministracion.setOpaque(true);
        btnUsuarioAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioAdministracionActionPerformed(evt);
            }
        });
        jPanel1.add(btnUsuarioAdministracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 180, 90));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 63, 100));
        jLabel9.setText("MY STORE");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 20));

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 8)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 63, 100));
        jLabel10.setText("MY STORE");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jLabel1.setBackground(new java.awt.Color(255, 255, 51));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 80));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 560, 10));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (8).png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 37, 60));

        jLabel11.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 63, 100));
        jLabel11.setText("MY STORE");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuarioCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioCajaActionPerformed
        // TODO add your handling code here:
        //cambiarNivel(1);
        this.revalidarVista();
        this.vGeneral.activarVistaUsuario(1);
        this.dispose();
    }//GEN-LAST:event_btnUsuarioCajaActionPerformed

    private void btnUsuarioAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioAlmacenActionPerformed
        // TODO add your handling code here:
        //cambiarNivel(2);   
        this.revalidarVista();
        this.vGeneral.activarVistaUsuario(2);
        this.dispose();
    }//GEN-LAST:event_btnUsuarioAlmacenActionPerformed

    private void btnUsuarioAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioAdministracionActionPerformed
        // TODO add your handling code here:
        //cambiarNivel(3);   
        this.revalidarVista();
        this.vGeneral.activarVistaUsuario(3);
        this.dispose();
    }//GEN-LAST:event_btnUsuarioAdministracionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dvgSuper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dvgSuper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dvgSuper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dvgSuper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dvgSuper dialog = new dvgSuper(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUsuarioAdministracion;
    private javax.swing.JButton btnUsuarioAlmacen;
    private javax.swing.JButton btnUsuarioCaja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
