/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JPanel;

/**
 *
 * @author diego
 */
public class lateralCajero extends javax.swing.JFrame {
    
    //JFrame de los botones laterales
    /***     
    private ticket FTicket;
    private verDisponibilidad FVerDisponibilidad;
    private cobrarCuenta FCobrarCuenta;
    private capturarDescuento FCapturarDescuento;
    private cambiarCliente FCambiarCliente;
    */
    
    private dlcAplicarDescuento dcAplicarDescuento;
    private dlcCambiarCliente dcCambiarCliente;
    private dlcCobrarCuenta dcCobrarCuenta;
    private dlcTicket dcTicket;
    private dlcVerDisponibilidad dcVerDisponibilidad;
    private dlcCorteCaja dcCorteCaja;

    /**
     * Creates new form lateralCajero
     */
    public lateralCajero() {
        initComponents();
        
        //Agregar controlador para acciones adcionales
    }
    
    public JPanel getPanelLateralCajero(){ return this.panelLateralCajero;}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLateralCajero = new javax.swing.JPanel();
        btnAplicarDescuento = new javax.swing.JButton();
        btnCambiarCliente = new javax.swing.JButton();
        btnVerDisponibilidad = new javax.swing.JButton();
        btnReimprimirUltimoTicket = new javax.swing.JButton();
        btnCancelarCuentaActual = new javax.swing.JButton();
        btnCancelarProducto = new javax.swing.JButton();
        btnCobrarCuenta = new javax.swing.JButton();
        btnCorteCaja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLateralCajero.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones de Caja", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Slab", 1, 14))); // NOI18N

        btnAplicarDescuento.setBackground(new java.awt.Color(204, 204, 204));
        btnAplicarDescuento.setFont(new java.awt.Font("Roboto Slab", 0, 14)); // NOI18N
        btnAplicarDescuento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (23).png"))); // NOI18N
        btnAplicarDescuento.setText("Aplicar descuento");
        btnAplicarDescuento.setOpaque(true);
        btnAplicarDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarDescuentoActionPerformed(evt);
            }
        });

        btnCambiarCliente.setBackground(new java.awt.Color(204, 204, 204));
        btnCambiarCliente.setFont(new java.awt.Font("Roboto Slab", 0, 14)); // NOI18N
        btnCambiarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (31).png"))); // NOI18N
        btnCambiarCliente.setText("Cambar cliente");
        btnCambiarCliente.setOpaque(true);
        btnCambiarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarClienteActionPerformed(evt);
            }
        });

        btnVerDisponibilidad.setBackground(new java.awt.Color(204, 204, 204));
        btnVerDisponibilidad.setFont(new java.awt.Font("Roboto Slab", 0, 14)); // NOI18N
        btnVerDisponibilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (32).png"))); // NOI18N
        btnVerDisponibilidad.setText("Ver disponibilidad");
        btnVerDisponibilidad.setOpaque(true);
        btnVerDisponibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDisponibilidadActionPerformed(evt);
            }
        });

        btnReimprimirUltimoTicket.setBackground(new java.awt.Color(204, 204, 204));
        btnReimprimirUltimoTicket.setFont(new java.awt.Font("Roboto Slab", 0, 14)); // NOI18N
        btnReimprimirUltimoTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (29).png"))); // NOI18N
        btnReimprimirUltimoTicket.setText("Reimprimir ultimo ticket");
        btnReimprimirUltimoTicket.setOpaque(true);
        btnReimprimirUltimoTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReimprimirUltimoTicketActionPerformed(evt);
            }
        });

        btnCancelarCuentaActual.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelarCuentaActual.setFont(new java.awt.Font("Roboto Slab", 0, 14)); // NOI18N
        btnCancelarCuentaActual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (28).png"))); // NOI18N
        btnCancelarCuentaActual.setText("Cancelar cuenta actual");
        btnCancelarCuentaActual.setOpaque(true);
        btnCancelarCuentaActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCuentaActualActionPerformed(evt);
            }
        });

        btnCancelarProducto.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelarProducto.setFont(new java.awt.Font("Roboto Slab", 0, 14)); // NOI18N
        btnCancelarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (27).png"))); // NOI18N
        btnCancelarProducto.setText("Cancelar un producto");
        btnCancelarProducto.setOpaque(true);
        btnCancelarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarProductoActionPerformed(evt);
            }
        });

        btnCobrarCuenta.setBackground(new java.awt.Color(51, 255, 51));
        btnCobrarCuenta.setFont(new java.awt.Font("Roboto Slab", 0, 14)); // NOI18N
        btnCobrarCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (16).png"))); // NOI18N
        btnCobrarCuenta.setText("Cobrar cuenta");
        btnCobrarCuenta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnCobrarCuenta.setOpaque(true);
        btnCobrarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarCuentaActionPerformed(evt);
            }
        });

        btnCorteCaja.setBackground(new java.awt.Color(255, 0, 0));
        btnCorteCaja.setFont(new java.awt.Font("Roboto Slab", 0, 14)); // NOI18N
        btnCorteCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/pngegg (15).png"))); // NOI18N
        btnCorteCaja.setText("Corte de caja");
        btnCorteCaja.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnCorteCaja.setOpaque(true);
        btnCorteCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorteCajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLateralCajeroLayout = new javax.swing.GroupLayout(panelLateralCajero);
        panelLateralCajero.setLayout(panelLateralCajeroLayout);
        panelLateralCajeroLayout.setHorizontalGroup(
            panelLateralCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLateralCajeroLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(panelLateralCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReimprimirUltimoTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelarCuentaActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerDisponibilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCambiarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAplicarDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLateralCajeroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCobrarCuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCorteCaja)
                .addGap(13, 13, 13))
        );
        panelLateralCajeroLayout.setVerticalGroup(
            panelLateralCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLateralCajeroLayout.createSequentialGroup()
                .addGroup(panelLateralCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCobrarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCorteCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(btnCancelarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelarCuentaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReimprimirUltimoTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVerDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCambiarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAplicarDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        getContentPane().add(panelLateralCajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAplicarDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarDescuentoActionPerformed
        // TODO add your handling code here:
        /** 
        FCapturarDescuento = new capturarDescuento();
        FCapturarDescuento.setLocationRelativeTo(null);
        FCapturarDescuento.setVisible(true);
        */
        
        this.dcAplicarDescuento = new dlcAplicarDescuento (new javax.swing.JFrame(), true);
        this.dcAplicarDescuento.setLocationRelativeTo(null);
        this.dcAplicarDescuento.setVisible(true);
        
    }//GEN-LAST:event_btnAplicarDescuentoActionPerformed

    private void btnCambiarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarClienteActionPerformed
        // TODO add your handling code here:
        /** 
        FCambiarCliente = new cambiarCliente();
        FCambiarCliente.setLocationRelativeTo(null);
        FCambiarCliente.setVisible(true);
        */
        this.dcCambiarCliente = new dlcCambiarCliente (new javax.swing.JFrame(), true);
        this.dcCambiarCliente.setLocationRelativeTo(null);
        this.dcCambiarCliente.setVisible(true);
        
    }//GEN-LAST:event_btnCambiarClienteActionPerformed

    private void btnVerDisponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDisponibilidadActionPerformed
        // TODO add your handling code here:
        /** 
        FVerDisponibilidad = new verDisponibilidad();
        FVerDisponibilidad.setLocationRelativeTo(null);
        FVerDisponibilidad.setVisible(true);
        */
        
        
        this.dcVerDisponibilidad = new dlcVerDisponibilidad (new javax.swing.JFrame(), true);
        this.dcVerDisponibilidad.setLocationRelativeTo(null);
        this.dcVerDisponibilidad.setVisible(true);
    }//GEN-LAST:event_btnVerDisponibilidadActionPerformed

    private void btnReimprimirUltimoTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReimprimirUltimoTicketActionPerformed
        // TODO add your handling code here:
        /**
        FTicket = new ticket();
        FTicket.setLocationRelativeTo(null);
        FTicket.setVisible(true);
        */
        this.dcTicket = new dlcTicket (new javax.swing.JFrame(), true);
        this.dcTicket.setLocationRelativeTo(null);
        this.dcTicket.setVisible(true);
    }//GEN-LAST:event_btnReimprimirUltimoTicketActionPerformed

    private void btnCancelarCuentaActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCuentaActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarCuentaActualActionPerformed

    private void btnCancelarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarProductoActionPerformed

    private void btnCobrarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarCuentaActionPerformed
        // TODO add your handling code here:        
        this.dcCobrarCuenta = new dlcCobrarCuenta(new javax.swing.JFrame(), true);
        this.dcCobrarCuenta.setLocationRelativeTo(null);
        this.dcCobrarCuenta.setVisible(true);
    }//GEN-LAST:event_btnCobrarCuentaActionPerformed

    private void btnCorteCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorteCajaActionPerformed
        // TODO add your handling code here:
        this.dcCorteCaja = new dlcCorteCaja(new javax.swing.JFrame(), true);
        this.dcCorteCaja.setLocationRelativeTo(null);
        this.dcCorteCaja.setVisible(true);
    }//GEN-LAST:event_btnCorteCajaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lateralCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lateralCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lateralCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lateralCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lateralCajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicarDescuento;
    private javax.swing.JButton btnCambiarCliente;
    private javax.swing.JButton btnCancelarCuentaActual;
    private javax.swing.JButton btnCancelarProducto;
    private javax.swing.JButton btnCobrarCuenta;
    private javax.swing.JButton btnCorteCaja;
    private javax.swing.JButton btnReimprimirUltimoTicket;
    private javax.swing.JButton btnVerDisponibilidad;
    private javax.swing.JPanel panelLateralCajero;
    // End of variables declaration//GEN-END:variables
}
